version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digium
    container_name: digium-app
    restart: unless-stopped
    working_dir: /app
    command: bash -c 'php artisan serve --host=0.0.0.0 --port=8181'
    ports:
      - "8009:8181"
